### ISSUE TITLE
$refs in parameter is not processed

### ISSUE THREAD

**Issue by ioggstream** [koxudaxi/fastapi-code-generator#24]
## I expect

$refs in parameters to be processed, eg

```
paths:
  /foo:
    parameters:
    - $ref: '#/components/parameters/MyParam'
components:
  parameters:
    MyParam:
      name: foo
      schema:
        type: string
```

## Instead

I get KeyError

```
  File "/usr/local/lib/python3.8/site-packages/fastapi_code_generator/parser.py", line 207, in get_parameter_type
    schema: JsonSchemaObject = JsonSchemaObject.parse_obj(parameter["schema"])
KeyError: 'schema'
```

**Comment by koxudaxi** [comment]
@ioggstream 
Thank you for creating this issue.
We should support `$ref` in parameters.

**Comment by ioggstream** [comment]
A solution could be to resolve all the $refs and then run the vanilla parser, which will then be `ref` - free.

WDYT?

**Comment by koxudaxi** [comment]
@ioggstream 
I think it's good :nerd_face:

**Comment by slym** [comment]
I'm facing the same issue with latest version. Is it supposed to be fixed or are you still working on it ?

**Comment by koxudaxi** [comment]
@slym 
Yes, I'm working on it.
I must resolve some problems.
1. datamodel-code-generator don't parse `/components/parameters` (fastapi-code-generator use datamodel-code-generator to generate models)
2. fastapi-code-generator can't get parse name from datamodel-code-generator. (duplicated models will be renamed)

I will update datamodel-code-generator for compatibility :)

**Comment by koxudaxi** [comment]
@ioggstream @slym 
I have released  a new version as `0.0.16`

This version doesn't parse complex models perfectly. But, I guess covering many cases

**Comment by slym** [comment]
I confirm it is now working well with version 0.0.16 even with some nested refs. Great work ! Thanks.

**Comment by ioggstream** [comment]
Thanks! As it still does not support remote refs, I'll close this and file another! Great work!

**Comment by oktavlachs** [comment]
Hey @koxudaxi @ioggstream,
thank you so much for your work on this project, it really helps a lot!
Today I ran into this issue with a url ref and thought it might be a bug within the scope of this thread:

```
paths:
  /{supiOrSuci}/security-information-rg:
    get:
      summary: Get authentication data for the FN-RG
      operationId: GetRgAuthData
      tags:
        - Get Auth Data for FN-RG
      parameters:
        - name: plmn-id
          in: query
          description: serving PLMN ID
          content:
            application/json:
              schema:
                $ref: 'http://localhost:8081/29.571/16.7.0/TS29571_CommonData.yaml#/components/schemas/PlmnId'
```

Error was:
```
site-packages/fastapi_code_generator/parser.py", line 293, in get_parameter_type
    schema: JsonSchemaObject = JsonSchemaObject.parse_obj(parameter["schema"])
KeyError: 'schema'
```
Should your gernerator also cover this nested content type?
Thanks!
