### ISSUE TITLE
[] in query parameter name generates code that cannot be formatted

### ISSUE THREAD

**Issue by Skyross** [koxudaxi/fastapi-code-generator#328]
When you have `[]` as prarameter name it fails to generate correct code. See this part of OpenAPI schema:

```yaml
parameters:
  - in: query
    name: color[]
    schema:
      type: array
      items:
        type: string
```

Possible solutions:
1. Correct schema to not use `[]`
2. Patch template to strip `[]` but handle possible name collisions like `color` and `color[]`
3. Add some `--no-code-format` flag to allow generate invalid code to fix it later manually

What do you think about it?
