### ISSUE TITLE
Support remote $ref-s

### ISSUE THREAD

**Issue by ioggstream** [koxudaxi/fastapi-code-generator#51]
## I expect

Remote $refs in parameters to be processed, eg

```
paths:
  /foo:
    parameters:
    - $ref: 'https://schema.example#/components/parameters/MyParam'
```

and in schema.example

```
components:
  parameters:
    MyParam:
      name: foo
      schema:
        type: string
```

## Instead

I get NotImplementedError ;)
